//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eden
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public int id { get; set; }
        public string MaChamCong { get; set; }
        public int idNguoiDung { get; set; }
        public System.DateTime NgayChamCong { get; set; }
        public Nullable<System.TimeSpan> GioDangNhap { get; set; }
        public Nullable<System.TimeSpan> GioDangXuat { get; set; }
        public string CaLamViec { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
