//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eden
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public int id { get; set; }
        public string MaLuong { get; set; }
        public int idThongTinNhanVien { get; set; }
        public string ThangNam { get; set; }
        public decimal LuongCoDinh { get; set; }
        public decimal TongDoanhSo { get; set; }
        public Nullable<decimal> PhatDiMuon { get; set; }
        public Nullable<decimal> PhatNghiBuoi { get; set; }
        public Nullable<decimal> TroCap { get; set; }
        public Nullable<decimal> Thuong { get; set; }
        public decimal TongLuong { get; set; }
        public System.DateTime NgayTinhLuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual THONGTINNHANVIEN THONGTINNHANVIEN { get; set; }
    }
}
