//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eden
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINNHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINNHANVIEN()
        {
            this.CHAMCONGs = new HashSet<CHAMCONG>();
            this.LUONGs = new HashSet<LUONG>();
        }
    
        public int id { get; set; }
        public string MaNhanVien { get; set; }
        public int idNguoiDung { get; set; }
        public decimal LuongCoDinh { get; set; }
        public System.DateTime NgayBatDauLam { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONG> LUONGs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
